Banner management
ONSdigital/response-operations-ui pull request #586
Opened 2021-01-28 15:46 UTC by insacuri

# Motivation and Context

# What has changed

# How to test?

# Links

2021-02-08 10:34 UTC, warrenbailey commented
/deploy baileyw

2021-02-08 12:02 UTC, warrenbailey requested changes

2021-02-08 13:28 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        flash('The alert has been removed')
This one is in the design.  I'll mention this along with the use of the word alert or banner

2021-02-08 13:30 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        logger.info("Removing active status from banner")
Yup, done

2021-02-08 13:30 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        flash("Banner text somehow not found on publish.  Please try again.")
Done

2021-02-08 13:31 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        flash("Something went wrong setting the banner")
That's fair.  I went back and fourth on the wording but the simple one is best I think.

2021-02-08 13:31 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        flash("Something went wrong setting the banner")
Done

2021-02-08 13:31 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        flash("Banner text somehow not found on publish.  Please try again.")
Done

2021-02-11 10:45 UTC, insacuri commented on response_operations_ui/views/admin.py
> +        flash('The alert has been removed')
We're going with alert.  I've changed all uses of the word banner in the text to alert

2021-02-11 14:52 UTC, warrenbailey approved these changes

2021-02-24 13:40 UTC, merged