Update design system to v70
ONSdigital/response-operations-ui pull request #923
Opened 2024-03-18 12:31 UTC by matthew-robinson-ons

# What and why?
This Pr updated the design system to the latest available version at the time. 
Strong tags in headings are now used to highlight so these have been removed from the code to prevent any unintended Ui changes. 
# How to test?
Run the app and check functionality and UI, Pagination headings should display the same as before. 
# Jira
https://jira.ons.gov.uk/browse/RAS-1094

2024-03-18 15:55 UTC, arroyoAle approved these changes
tests pass, changes look good, nothing seems to have changed in the UI

2024-03-18 17:14 UTC, LJBabbage requested changes
Looks like you might have missed this change https://github.com/ONSdigital/design-system/pull/3047. Not sure about those strong tags, I can see what they have done, but doesn't that stop them being bold?

2024-03-19 09:31 UTC, matthew-robinson-ons commented
> Looks like you might have missed this change [ONSdigital/design-system#3047](https://github.com/ONSdigital/design-system/pull/3047). Not sure about those strong tags, I can see what they have done, but doesn't that stop them being bold?

Will take a look at the link, with the strong tags, removing them had no visual change, i believe H3 is already bold so the strong tags were redundant anyway.

2024-03-20 14:43 UTC, matthew-robinson-ons commented on response_operations_ui/templates/account/my-account.html
> +        <dt class="ons-metadata__term ons-grid__col ons-col-4@m"><strong>Email address:</strong></dt>
Off the back of the fronstage PR have made these changes as well. This keeps the same visual format as before it seems ons-metadata__term was adding bold text styling and is no longer doing that.

2024-03-20 15:18 UTC, LJBabbage approved these changes

2024-03-21 09:33 UTC, merged